import time

### MAD LIBS ###
###source:http://www.rainbowresource.com/products/018838i1.jpg

print("Give me an noun.")
noun1= input()
print("Another noun.")
noun2= input()
print("Now give me a plural noun.")
pluralnoun1= input()
print("give me an adjective")
adj1= input()
print("give me another adjective.")
adj2= input()
print("give me another adjective.")
adj3= input()
print("give me a noun")
noun3= input()
print("give me an adverb.")
adv1= input()
print("give me a plural noun.")
pluralnoun2= input()
print("give me an adjective.")
adj4= input()
print("give me another adjective.")
adj5= input()
print("give me a part of the body (plural)")
bp1= input()
print("give me another part of body (plural)")
bp2= input()
print("give me a plural noun.")
pluralnoun3= input()
print("give me a noun")
noun4= input()
print("now give me one more body part.")
bp3 = input()

print("Our dining room" + noun1 +" used to be a war " + noun2 + ".")
print("I thought the battles about correct table " + pluralnoun1 + " would never end.")
print("It was us kids versus Mom, and it seemed like a fight that would last to the" + adj1 + " end")
print("But tonight dad finally negotiated a/an " + adj2 + " truce,")
print("and we negotiated a/an " + adj3 + " peace " + noun3 + ".")
print("mom promised to no longer get " + adv1 + " upset and shoot us dirty " + pluralnoun2 + "and make" + adj4 + "remarks when we do" + adj5 + "things she doesent like.")
print("We agreed to:")
print("1.) Use napkins to wipe our " + bp1 + " and not our " + pluralnoun3 + ".")
print("2. Keep your " + bp2 + " off the table.")
print("3. Not use our " + bp3 + " to pick up " + pluralnoun3 + " from our plates- except for sanwiches or pieces of" + noun4)
print("4. never talk with food in our" + bp3 + ".")

time.sleep(100)
